### ISSUE TITLE
Scrolling in Event page on iOS/Safari is buggy

### ISSUE THREAD

**Issue by emunsing** [dproctor/trashy#15]
Sometimes I seem to be grabbing an element which only moves part of the table (not allowing me to get to the bottom of the event list). I'm not good enough with HTML to easily fix this.

https://github.com/dproctor/trashy/assets/6070874/59f1b84f-76b2-4ab4-80fb-c5868990b2ea

**Comment by dproctor** [comment]
I'm going to leave as is for now, as this is using standard phoenix components, and there isn't an easy fix that still maintains usability.
